### PR TITLE
Bio.PDB.Atom.coord is numpy array

### PR DESCRIPTION
**Pull request by hongbo-zhu-cn**
Hi, 
the coordinates for an atom in Bio.PDB.Atom is an instance of Numpy Array. Currently it is a mixture of vector and list. This may lead to unwanted behaviors when atom coordinates are concerned.
best,

### CODE REVIEW

**Comment by clauswilke** [comment]
Thanks for this patch.
Could you provide a minimal example showing how the current implementation causes unwanted behaviors? Maybe submitted separately as an issue?

**Comment by clauswilke** [comment]
I don't see why the change in line 98 is needed. The function `calculateCoordinates` does not create any coordinate vectors from scratch but rather obtains them from atoms or using the `Vector` constructor. Please check whether you can remove your change in line 98 and have things still work.

I agree the changes in lines 980 to 982 are needed.

**Comment by hongbo-zhu-cn** [comment]
Because function `calculateCoordinates()` returns D as an instance of Bio.PDB.Vector, which is not an array. This still cause the ValueError (I just double checked). But now I change it to `D.get_array()` instead of using type conversion. This shall look neater.

**Comment by clauswilke** [comment]
Yes, I prefer this, thanks!

**Pull request merged**
