### PR TITLE
Added upper limit to Biopython version

### PR DESCRIPTION
**Pull request by George3d6**
Doesn't work with the latest biopython version (1.76) due to issues importing `bio.PDB.Vector`, not 100% sure how to fix those without breaking something else, but I think putting and upper limit of the biopython would help for now (1.71.0 is the latest version I found that works).

### CODE REVIEW

**Comment by clauswilke** [comment]
Which version of the code are you using? We merged a fix for this recently, I believe (#11). I don't ever use this code anymore, but I'd rather fix it to work with the latest version of biopython than put a version restriction on it.

**Comment by George3d6** [comment]
`PeptideBuilder.__version__` says `1.0.4`, which seems to be the latest version on pypi.
Even if you want to keep it up to date, it might be worth adding "latest version it was tested with" to the README, since it depends on a library with an unstable API.

**Comment by clauswilke** [comment]
Please try github master. I know I need to do a new release, I just haven't gotten around to it yet.

**Comment by mtien** [comment]
I forgot about this request. 

The newest version of biopython changed the class from Bio.PDB.Vector to from Bio.PDB.vector**s**. Import statement with the newest biopython version should be 
from Bio.PDB.vectors import *

**Comment by clauswilke** [comment]
That has been fixed already:
https://github.com/mtien/PeptideBuilder/blob/314611d1f377edfe6b6ea7a48181678b6c025faf/PeptideBuilder/PeptideBuilder.py#L22

I'm going to close this PR because the right way forward is to fix PeptideBuilder so it works with the latest releases of the required dependencies.

**Pull request closed without merging**
